FROM python:2-slim

LABEL maintainer="Ajan Lal Shrestha<ajan.shresh@gmail.com>"

RUN apt-get update -y && \
  apt-get install --no-install-recommends -y \
  libxml2-dev \
  libxslt-dev \
  python-dev &&\
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src
WORKDIR /usr/src
